<div class="section-overlay-actions<#= responsive ? ' responsive-overlay':''#>">
	<div class="section-description"><?php echo __( 'This is a Linked section', THEME_DOMAIN ); ?></div>
	<button class="grey-button ghost-button click" data-fn="openSectionModal"><?php echo __( 'Replace', THEME_DOMAIN ); ?></button>
	<button class="orange-button click" data-fn="enterEditMode"><?php echo __( 'Edit Section', THEME_DOMAIN ); ?></button>
	<button class="grey-button ghost-button click" data-fn="unlink"><?php echo __( 'Unlink', THEME_DOMAIN ); ?></button>
</div>
