<div class="ttd-icon-menu">
	<div class="ttd-icon ttd-icon-blue">
		<?php Thrive_Views::svg_icon( 'builder-logo' ); ?>
	</div>
</div>
<div class="ttd-sidebar-container"></div>
<div class="ttd-sidebar-container ttd-skins-container"></div>
<div class="ttd-main-container"></div>
<div class="ttd-preview-container"></div>

<div id="ttd-modals"></div>

<div id="ttd-notification-box"></div>

<script src="https://fast.wistia.com/embed/medias/dinfo5vmt8.jsonp" async></script>
<script src="https://fast.wistia.com/embed/medias/tv2jgkxyb3.jsonp" async></script>
<script src="https://fast.wistia.com/assets/external/E-v1.js" async></script>
