<div class="click ttd-ss" data-fn="toggle_skin_view">
    <h1>
        <span>
            <?php echo __( 'Current Theme', THEME_DOMAIN ); ?>:
        </span>
		<strong><#= this.model.get('name') #></strong>
    </h1>
    <div class="dots">
		<span></span>
		<span></span>
		<span></span>
		<span></span>
		<span></span>
		<span class="span-w-text"><?php echo __( 'Manage', THEME_DOMAIN ); ?></span>
    </div>
</div>
