<div class="ttd-wizard-woo-box fw ttd-wizard-clip clip-woo placeholder">
	<img class="ttd-wizard-splash" src="<?php echo THEME_URL . '/inc/assets/images/wizard/woo-commerce.png' ?>" width="254" height="137">
	<# if ( this.hasTemplates ) { #>
		<h2 class="ttd-wizard-title mt-40"><?php echo esc_html__( 'WooCommerce is Active!', THEME_DOMAIN ); ?></h2>
		<div class="ttd-wizard-next-steps mt-30">
			<a href="<#= this.shopUrl #>" target="_blank" class="ttd-next-option bg-white ttd-btn blue">
				<?php Thrive_Views::svg_icon( 'icon-preview' ); ?>
				<?php echo esc_html__( 'Preview My Shop', THEME_DOMAIN ); ?>
			</a>
			<?php /* wistia video trigger needs to be a <span> element */ ?>
			<?php //Remove it for now because we don't have the video yet ?>
<!--			<span class="ttd-wizard-finished-video click ttd-btn blue fill ttd-next-option wistia_embed wistia_async_dinfo5vmt8 popover=true popoverContent=html">-->
<!--			--><?php //Thrive_Views::svg_icon( 'icon-video' ); ?><!----><?php //echo esc_html__( 'WooCommerce walkthrough', THEME_DOMAIN ); ?>
<!--		</span>-->
		</div>
	<# } else { #>
		<h2 class="ttd-wizard-title mt-40"><?php echo esc_html__( 'Visual WooCommerce Editing is Here', THEME_DOMAIN ); ?></h2>
		<p class="ttd-wizard-desc mt-20 mb-0"><?php echo sprintf( esc_html__( 'Click the button below to download and activate WooCommerce shop %sbuilding in the theme.', THEME_DOMAIN ), '<br>' ); ?></p>
		<button class="ttd-finish-button ttd-btn click blue fill mt-15 loader-absolute small"
		        data-fn="downloadTemplates"><?php echo __( 'Download and activate WooCommerce shop templates', THEME_DOMAIN ); ?></button>
	<# } #>
</div>