<div class="ttd-skin-item-template <# if ( this.model.get( 'preview_open' ) ) { #>ttd-preview-open<# } #> <# if ( this.model.is_active() ) { #>active<# } #> click" data-fn="change_skin">
	<span class="ttd-active-mark"><?php echo __( 'Active', THEME_DOMAIN ); ?></span>
	<# if ( this.model.get( 'preview_open' ) ) { #>
	      <span class="ttd-preview-mark"><?php echo __( 'Preview Open', THEME_DOMAIN ); ?></span>
    <# } #>
    <div class="ttd-skin-item-name"><#= this.model.get('name') #></div>
	<div class="ttd-action-buttons">
		<div class="click" data-fn="change_skin_preview"><?php echo __( 'Preview', THEME_DOMAIN );?></div>
	</div>
</div>